### ISSUE TITLE
DB migration Tools related

### ISSUE THREAD

**Issue by nammadhu** [samanazadi1996/Sam.CleanArchitecture#8]
Its nice to have the  [bat file tool](https://github.com/samanazadi1996/Sam.CleanArchitecture/commit/14606e45db4f155fd3226a35203790a8fa09df47) but i noticed little more improvement as here,

1><img width="860" alt="image" src="https://github.com/samanazadi1996/Sam.CleanArchitecture/assets/3640748/981de032-ed05-42c5-9060-37eebe0d947a">
To fix the red error,
After modifying the .bat "source" to "CleanArchitecture" its working fine(mine name is default) 
<img width="874" alt="image" src="https://github.com/samanazadi1996/Sam.CleanArchitecture/assets/3640748/1f852f11-820d-45f5-80a8-22bd07e68e79">

May be a slight improvement needed I guess
2>Also after add-migration, 1-2 more step like verify in VS/code then show the command for update-database also, either execute here itself in CLI or copy & paste to package manager console also makes smooth & attactive...
ex: update-database -Context ApplicationDbContext .........

**Comment by samanazadi1996** [comment]
Unfortunately, the name of the project(in bat file) is taken from the name of the folder where the project is located.

This problem does not exist when creating a new project.
And I will also solve this problem in the next version

**Comment by samanazadi1996** [comment]
This problem is completely solved, you can and it can be used in the next version of the package

[AddMigration.Persistence.bat](https://github.com/samanazadi1996/Sam.CleanArchitecture/blob/master/Templates/ca-tools/Tools/AddMigration.Persistence.bat)

[AddMigration.Identity.bat](https://github.com/samanazadi1996/Sam.CleanArchitecture/blob/master/Templates/ca-tools/Tools/AddMigration.Identity.bat)

[AddMigration.FileManager.bat](https://github.com/samanazadi1996/Sam.CleanArchitecture/blob/master/Templates/ca-tools/Tools/AddMigration.FileManager.bat)
